### ISSUE TITLE
Flatten Directory Structure

### ISSUE THREAD

**Issue by jonathanamartin** [jenkinsci/ibm-ucdeploy-pipeline-plugin#5]
I recall in an old freestyle job I had there was an option to create a new UDeploy component version with files in a flat directory structure or as they were matched with the `fileIncludePatterns` property.

I've got Jenkins integrated with UDeploy.  However, the `target` directory from my Maven project is also being added to the component version files.

Was the "flatten directory structure" feature removed or is this still possible?

**Comment by jonathanamartin** [comment]
I believe it was the offset.  Currently being defaulted to `""`.

https://github.com/jenkinsci/ibm-ucdeploy-pipeline-plugin/blob/master/src/main/java/com/urbancode/jenkins/plugins/ucdeploy/VersionHelper.java#L243

**Comment by nhmathis** [comment]
Hi,

I cannot find a time where the offset was not set to `""`. However, you can specify a the root import directory using the `baseDir` property which should further restrict the imports. In addition, the `fileExcludePatterns` can also be used to ignore all contents in the `target` dir. 

You will need to create a RFE for the flatten directory structure feature.

**Comment by jonathanamartin** [comment]
Understood.  Where do I submit an RFE?

**Comment by nhmathis** [comment]
RFEs can be made here: https://www.ibm.com/developerworks/rfe/

We'll keep the issue open to document the request here as well.

**Comment by jonathanamartin** [comment]
Sounds good.  Thanks.

**Comment by jonathanamartin** [comment]
Couldn't find the plugin or UDeploy for that matter in the "submit" form.   Tried to submit under another product but had odd validation errors.

**Comment by nhmathis** [comment]
There should be an option of the variation `UrbanCode` or `UrbanCode-Integrations`

**Comment by jonathanamartin** [comment]
Thanks that helped.  Here it is:
http://www.ibm.com/developerworks/rfe/execute?use_case=viewRfe&CR_ID=105932

**Comment by nhmathis** [comment]
We've determined that this functionality can be achieved today through the Jenkins build process. As this functionality would be redundant, we do not plan to add it to our Jenkins plugin.
